### ISSUE TITLE
<Queue>.remove does not work

### ISSUE THREAD

**Issue by inhydrox** [Solaris9/erela.js#43] opened 2020-08-29 08:10 UTC
Hey <Queue>.remove does not work 
![Image](https://user-images.githubusercontent.com/40756526/91632242-34335b00-e9fd-11ea-8476-5ac2d0883614.gif)

**Comment by inhydrox** [comment] 2020-08-29 08:12
My erela version: 2.0.0-beta.5

**Comment by Anish-Shobith** [comment] 2020-08-29 08:36
It's impossible to say with the amount of information you provided please link code or provide code for us to reproduce the issue

**Comment by inhydrox** [comment] 2020-08-30 02:35
```js
     const amount = Math.round(Number(args[0]) || 0) - 1;   
     
     player.queue.remove(amount);
```

**Comment by Solaris9** [comment] 2020-08-31 00:09
I am unable to reproduce this with my code, are you able to provide your own code so I can test it?

**Comment by Anish-Shobith** [comment] 2020-08-31 16:12
Closing this issue , if the issue persist please re open the issue and provide more code for us to check.

**Closed by Anish-Shobith** 2020-08-31 16:12 UTC
Labels: invalid
